package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SampleMavenbuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SampleMavenbuild")) {
    check(publishArtifacts == PublishMode.NORMALLY_FINISHED) {
        "Unexpected option value: publishArtifacts = $publishArtifacts"
    }
    publishArtifacts = PublishMode.SUCCESSFUL
}
